-- v1 backfill: committee detail + attendance + phones + officer primary_role
-- Generated 2026-04-21T00:45:04.849Z

BEGIN;

-- Committee detail
UPDATE committees SET description_md = 'Keeps the party''s governing documents current and correct. Reviews the bylaws annually, drafts amendments when needed, and is the final authority on what the party can and cannot do procedurally. Chaired by the Vice Chair because bylaws questions directly affect officer authority.', workflow = ARRAY['Review bylaws at least once per year; flag ambiguities or conflicts.','Draft proposed amendments; circulate to Executive Committee 30 days before vote.','Present amendments at a full EC meeting with required notice.','Maintain the canonical bylaws doc on the website and in the committee folder.']::text[], docs = '[{"name":"LJCDP Bylaws (current)","howto":"The canonical public version. Reference for any procedural question.","link":"https://www.louisvilledems.com/ljcdp-bylaws"},{"name":"KDP County Executive Committee Guide","howto":"How KDP expects county committees to operate. Use when your question isn''t covered in LJCDP bylaws.","link":"https://www.louisvilledems.com/s/CEC-Guide.pdf"}]'::jsonb, member_codes = ARRAY['Rick Adams','Idiris Ali','Julie Carr','Janice Dean','Seth Drake','Monica Flowers','Robin Foxx','Ruth Gao','Charlie Horton','Byron Hoskinson','Stephon Moore','Jeff Noble','Jason Perkey','Beth Thorpe','Mike Ward']::text[] WHERE code = 'BYLAWS';
UPDATE committees SET description_md = 'Identifies and recruits Democrats to run for office — Metro Council, state legislature, judicial, school board, and down-ballot races. Works alongside KDP''s candidate resources to make sure every winnable race has a credible Democrat on the ballot.', workflow = ARRAY['Maintain a rolling list of winnable and open seats by election cycle.','Identify target recruits from LD chairs, at-large members, and affiliated org leaders.','Run 1:1 recruitment conversations; connect recruits with KDP Campaign Guide and resources.','Hand recruits off to Events and Finance committees for fundraising support once they declare.']::text[], docs = '[{"name":"KDP Campaign Guide","howto":"Give to every recruit before they declare. Covers filing, finance reporting, ballot access.","link":"https://drive.google.com/file/d/1MXHig1rbASbTsK7Rl8yDMTfU4KHqYRVG/view"},{"name":"All KDP Candidate Resources","howto":"Full KDP resource folder. Share link with any serious candidate.","link":"https://drive.google.com/drive/folders/15gzUdpHwGOMVUzehaHiiUF-5uYjgjmpy"}]'::jsonb, member_codes = ARRAY['Rick Adams','Emily Ball','Brook Benningfield','Janice Dean','Monica Flowers','Tom Ridge','Ricky Santiago','Allison Wiseman']::text[] WHERE code = 'CANDIDATE_RECRUITMENT';
UPDATE committees SET description_md = 'Owns the party''s voice across owned, earned, and paid channels. Runs social (FB, IG, TikTok, X, Threads, Bluesky, YouTube), press, the email list, the website, and printed materials. Manages the digital ad program — including fundraising for the ad fund and producing creative for paid Meta campaigns. Built and maintains the Drive backend that powers louisvilledems.com and that every committee, LD, and candidate uses to find what they need. Enforces brand consistency across everything LDP sends out. Partners with the ad-hoc Branding committee on visual identity until the brand system is rolled out, then owns ongoing brand enforcement. See the dedicated Communications section above for the board-facing asks.', workflow = ARRAY['Maintain monthly content calendar across channels (site, IG, FB, email, TikTok, Threads, Bluesky, X, YouTube).','Run paid digital ad program: campaign planning, creative production, audience targeting, performance reporting back to the EC.','Fundraise specifically for the ad fund — separate ask from board dues / general operating dollars — so paid media scales with the cycle.','Maintain the Drive backend that powers the EC portal: folder structure, brand kit, event collateral library, ad assets, intake forms.','Triage press inquiries via communications@louisvilledems.com; draft responses for officer sign-off.','Process social/asset requests through the Event Request form — one intake, one approval path.','Train LD chairs and candidates on brand and message consistency.']::text[], docs = '[{"name":"Event Request form (intake for everything)","howto":"How LDs, candidates, and committees request social posts, graphics, calendar listings, printed materials, or pre-approved ads. Use this — don''t text Beth at 9pm.","link":"https://loukydemparty.fillout.com/eventrequest"},{"name":"Brand kit & assets folder","howto":"Logos, color palette, fonts, templates, photo library. Pull from here — don''t recreate.","link":"https://drive.google.com/drive/folders/135yaPswLTfcL2r8QuC1_kZrCA2S7aB1O"},{"name":"Press inquiries","howto":"Forward all press to comms email. Beth drafts the response, Chair signs off, Comms releases.","link":"mailto:communications@louisvilledems.com"},{"name":"DNC Security Checklist","howto":"Everyone with comms access runs through MFA, password manager, and phishing basics.","link":"https://democrats.org/wp-content/uploads/2025/07/2025-DNC-Security-Checklist-v4-6_2025.pdf"}]'::jsonb, member_codes = ARRAY['Merideth Booth','Monica Flowers','Blake Gerstner','Cori Geter','Jessica Haggy','Jason Perkey','Hallie Rice','Allison Wiseman']::text[] WHERE code = 'COMMUNICATIONS';
UPDATE committees SET description_md = 'Ad-hoc. Designs and revises the endorsement process itself — criteria, timeline, questionnaire, forum format, vote mechanics. Distinct from the standing Endorsement Committee, which executes the process each cycle. Will be one of the most important committees post-2026 primary, because everything we learn this cycle needs to feed back into process design for future endorsements.', workflow = ARRAY['Activate after each major election cycle (primary / general).','Collect feedback from standing Endorsement Committee members, candidates who sought endorsement, and LD chairs.','Identify what worked and what didn''t — timeline, questionnaire, forums, vote mechanics.','Draft process revisions; circulate to full EC for comment.','Present finalized process for EC vote before next cycle begins.','Hand updated process to the standing Endorsement Committee to execute.']::text[], docs = '[{"name":"LJCDP Bylaws","howto":"Endorsement process must stay consistent with bylaws. Bylaws Committee weighs in on any proposed change.","link":"https://www.louisvilledems.com/ljcdp-bylaws"}]'::jsonb, member_codes = ARRAY['Members TBD — named when the committee reconvenes']::text[] WHERE code = 'ENDORSEMENT_PROCESS';
UPDATE committees SET description_md = 'Plans and executes LDP signature events and fundraisers. Three subcommittees handle the flagship events: the Celebration of Democracy Dinner (annual signature dinner — last Saturday in March; rebrand to a permanent name, currently aiming at the Yarmuth Dinner, is in flight), Women Deliver Democracy, and Dems at the Downs. Coordinates with Finance on revenue targets.', workflow = ARRAY['Set annual calendar: Celebration of Democracy Dinner (March), WDD, Dems at the Downs, plus off-year meet-and-greets.','Assign subcommittee leads for each flagship event.','Coordinate with Finance on revenue targets and ticket pricing.','Partner with Communications on promotion and materials.','Debrief after each event; save notes in the folder.']::text[], docs = '[{"name":"Celebration of Democracy Dinner Subcommittee","howto":"Annual signature dinner — last Saturday in March. Largest fundraiser of the year. Rebrand to a permanent name (Yarmuth Dinner is the current direction) is in progress.","link":"https://drive.google.com/drive/folders/17KbK3cR3NVLep_o5PbY8t_bKm43ki7dM"},{"name":"Women Deliver Democracy","howto":"Women-focused event programming.","link":"https://drive.google.com/drive/folders/1TPT-_obSRP2STS5NteFEGFyrrmss4ueT"},{"name":"Dems at the Downs","howto":"Derby-season event.","link":"https://drive.google.com/drive/folders/1lcYEyzGc0IHzLb51-oawE1-pNSXKwoNj"},{"name":"Event Request form","howto":"LDs and candidates use this to get event support.","link":"https://loukydemparty.fillout.com/eventrequest"}]'::jsonb, member_codes = ARRAY['Idiris Ali','Emily Ball','Cassie Blausey','Janice Dean','Monica Flowers','Cori Geter','Byron Hoskinson','Stephon Moore','Lisa Norkus','Hallie Rice','Ricky Santiago','Jim Stammerman','Beth Thorpe']::text[] WHERE code = 'EVENTS';
UPDATE committees SET description_md = 'Manages LDP headquarters and physical assets. Lease, supplies, tech, and bookable space for committee meetings, candidate forums, and volunteer events. The invisible committee — you only notice them when something isn''t working.', workflow = ARRAY['Maintain HQ lease, supplies inventory, and AV/tech setup.','Manage booking calendar for HQ meeting space.','Coordinate with Events on space needs for fundraisers.','Flag maintenance and tech issues to Finance for budgeting.']::text[], docs = '[{"name":"HQ booking","howto":"Request space at HQ via the Event Request form.","link":"https://loukydemparty.fillout.com/eventrequest"}]'::jsonb, member_codes = ARRAY['John Anderson','Carolyn Benedict','Brook Benningfield','Blake Gerstner','Cori Geter','Jennifer Hardin','Hallie Rice','Beth Thorpe','Kenneth Washington']::text[] WHERE code = 'FACILITIES';
UPDATE committees SET description_md = 'Budget and financial controls. Sets annual fundraising targets, approves major expenditures, and works directly with the Treasurer on financial statements and KREF compliance. Oversight on all money in and out. Important context: KDP and the DNC together fund less than a fifth of party operating costs at every level — the bulk of LDP''s budget is raised locally through board dues, signature events, and donor cultivation. That''s why $10/month auto-pay and the $500 annual raise target sit on every board member.', workflow = ARRAY['Build annual budget with Treasurer at start of each year.','Review monthly financial statements before EC meeting.','Approve expenditures above the threshold set in bylaws.','Coordinate with Events on fundraiser targets.','Ensure KREF filings are on time.']::text[], docs = '[{"name":"Treasurer Reports","howto":"Monthly financial statements. Review before EC meeting.","link":"https://drive.google.com/drive/folders/1-UGKS4u_H6-tdbLzz725YBsOogFMR3xk"}]'::jsonb, member_codes = ARRAY['Carolyn Benedict','Blake Gerstner','Cori Geter','Charlie Horton','Robert Kahne','Stephon Moore','Lisa Norkus','Hallie Rice','Beth Thorpe']::text[] WHERE code = 'FINANCE';
UPDATE committees SET description_md = 'Drafts and maintains the LDP platform — what Louisville Democrats actually stand for. Translates national Democratic values into Louisville-specific priorities that candidates can run on. Revisits the platform every cycle.', workflow = ARRAY['Open the platform for revision at start of each cycle.','Gather input from LD chairs, affiliated caucuses, and member ideas.','Draft, circulate for comment, and present at EC for vote.','Publish updated platform; share with endorsed candidates as their starting point.']::text[], docs = '[]'::jsonb, member_codes = ARRAY['Janice Dean','Robin Foxx','Blake Gerstner','Byron Hoskinson','Robert Kahne','Emalee Morley','Hallie Rice','Tom Ridge','Kenneth Washington']::text[] WHERE code = 'PLATFORM';
UPDATE committees SET description_md = 'Strategic brand refresh. Modernizes how LDP looks and feels across every touchpoint — website, social, printed materials, event design. Post-merger work to unify the Louisville Democratic Party identity. Partners closely with Communications.', workflow = ARRAY['Audit current brand use across channels.','Develop updated visual system: logo variations, color palette, typography, photography.','Produce brand guidelines document.','Roll out in phases: digital first, then print, then HQ signage.','Train Communications team and candidates on brand use.']::text[], docs = '[]'::jsonb, member_codes = ARRAY['Rasean Crawley','Cori Geter','Jennifer Hardin','Stephon Moore','Jason Perkey','Ricky Santiago','Beth Thorpe','Allison Wiseman']::text[] WHERE code = 'BRANDING';
UPDATE committees SET description_md = 'Develops and delivers training programs for LD chairs, precinct captains, canvassers, and volunteers. Ensures every member of the org — new and experienced — knows how to do their job. Uses the LD Chair VoteBuilder Guide and Canvassing Guide as core curriculum.', workflow = ARRAY['Annual training calendar: new-LD-chair onboarding, precinct captain training, canvass training, VoteBuilder basics.','Deliver Canvass Training before every major campaign phase (primary, general).','Keep curriculum current — update guides as tools and tactics change.','Run buddy/mentor program for new LD chairs.']::text[], docs = '[{"name":"LDP Legislative District Organizing Guide","howto":"Core curriculum for new LD chairs.","link":"https://drive.google.com/file/d/1rjSsSO8b84-Gw3BhPW1A_diMNGTgY5Xo/view"},{"name":"LDP Canvassing Guide","howto":"One-pager every canvasser gets in their packet.","link":"https://drive.google.com/file/d/1tId_OBvdwa5TGME7LMIX26idTZ8iG_Dj/view"}]'::jsonb, member_codes = ARRAY['Rick Adams','Janice Dean','Monica Flowers','Byron Hoskinson','Lisa Norkus','Hallie Rice','Tom Ridge','Beth Thorpe','Kenneth Washington']::text[] WHERE code = 'TRAINING';
UPDATE committees SET description_md = 'Recruits, onboards, and retains volunteers. The feeder pipeline for everything else — without volunteers, no committee can deliver. Captures volunteer leads from canvass surveys and events, and matches them to LD chairs and committees by interest.', workflow = ARRAY['Maintain volunteer pipeline spreadsheet — everyone who said yes at an event or on a canvass.','Onboard new volunteers within 7 days: welcome, interest survey, LD introduction.','Match volunteers to LD chairs and committees by interest and geography.','Track retention; follow up with lapsed volunteers.','Coordinate with Training on volunteer skill-building.']::text[], docs = '[{"name":"Volunteer sign-up","howto":"Public volunteer intake form. Promote at every event.","link":"https://act.campaigndeputy.com/LDPVounteerSignup"},{"name":"Volunteer Committee email","howto":"Shared mailbox for volunteer inbound.","link":"mailto:volunteer@louisvilledems.com"}]'::jsonb, member_codes = ARRAY['Byron Hoskinson','Hallie Rice','Tom Ridge']::text[] WHERE code = 'VOLUNTEER';

-- Structured attendance
UPDATE ec_members SET attendance_present = 10, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Almaria' AND last_name = 'Baker';
UPDATE ec_members SET attendance_present = 5, attendance_excused = 1, attendance_absent = 4, attendance_eligible = 10 WHERE first_name = 'Dwan' AND last_name = 'Williams';
UPDATE ec_members SET attendance_present = 7, attendance_excused = 2, attendance_absent = 1, attendance_eligible = 10 WHERE first_name = 'Ricky' AND last_name = 'Santiago';
UPDATE ec_members SET attendance_present = 5, attendance_excused = 1, attendance_absent = 4, attendance_eligible = 10 WHERE first_name = 'Cassie' AND last_name = 'Blausey';
UPDATE ec_members SET attendance_present = 6, attendance_excused = 4, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Emalee' AND last_name = 'Morley';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 1, attendance_eligible = 9 WHERE first_name = 'Jim' AND last_name = 'Stammerman';
UPDATE ec_members SET attendance_present = 5, attendance_excused = 2, attendance_absent = 3, attendance_eligible = 10 WHERE first_name = 'Mitch' AND last_name = 'Smith';
UPDATE ec_members SET attendance_present = 6, attendance_excused = 1, attendance_absent = 3, attendance_eligible = 10 WHERE first_name = 'Ruth' AND last_name = 'Gao';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 0, attendance_absent = 1, attendance_eligible = 10 WHERE first_name = 'Brian' AND last_name = 'Sutton';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Julie' AND last_name = 'Carr';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 9 WHERE first_name = 'Jennifer' AND last_name = 'Hardin';
UPDATE ec_members SET attendance_present = 4, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 4 WHERE first_name = 'Larry' AND last_name = 'Owens';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 2, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Kathryn' AND last_name = 'Hargraves';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 2, attendance_eligible = 10 WHERE first_name = 'Jason' AND last_name = 'Perkey';
UPDATE ec_members SET attendance_present = 3, attendance_excused = 1, attendance_absent = 6, attendance_eligible = 10 WHERE first_name = 'Mike' AND last_name = 'Goetz';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 1, attendance_eligible = 9 WHERE first_name = 'Carolyn' AND last_name = 'Benedict';
UPDATE ec_members SET attendance_present = 4, attendance_excused = 3, attendance_absent = 3, attendance_eligible = 10 WHERE first_name = 'Colin' AND last_name = 'McDowell';
UPDATE ec_members SET attendance_present = 10, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Brook' AND last_name = 'Benningfield';
UPDATE ec_members SET attendance_present = 3, attendance_excused = 0, attendance_absent = 7, attendance_eligible = 10 WHERE first_name = 'John' AND last_name = 'Stovall';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 0, attendance_absent = 1, attendance_eligible = 10 WHERE first_name = 'Tyra' AND last_name = 'Thomas-Walker';
UPDATE ec_members SET attendance_present = 10, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Beth' AND last_name = 'Thorpe';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Byron' AND last_name = 'Hoskinson';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Blake' AND last_name = 'Gerstner';
UPDATE ec_members SET attendance_present = 1, attendance_excused = 0, attendance_absent = 9, attendance_eligible = 10 WHERE first_name = 'Nima' AND last_name = 'Kulkarni';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Robert' AND last_name = 'Kahne';
UPDATE ec_members SET attendance_present = 10, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Lisa' AND last_name = 'Tanner Norkus';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Logan' AND last_name = 'Gatti';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 1, attendance_absent = 1, attendance_eligible = 10 WHERE first_name = 'Joi' AND last_name = 'McAtee';
UPDATE ec_members SET attendance_present = 2, attendance_excused = 0, attendance_absent = 1, attendance_eligible = 3 WHERE first_name = 'Gerald' AND last_name = 'Joiner';
UPDATE ec_members SET attendance_present = 1, attendance_excused = 0, attendance_absent = 1, attendance_eligible = 2 WHERE first_name = 'Beverly' AND last_name = 'Chester Burton';
UPDATE ec_members SET attendance_present = 2, attendance_excused = 0, attendance_absent = 8, attendance_eligible = 10 WHERE first_name = 'Simeon' AND last_name = 'Pullum';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 2, attendance_eligible = 10 WHERE first_name = 'Roz' AND last_name = 'Welch';
UPDATE ec_members SET attendance_present = 6, attendance_excused = 0, attendance_absent = 4, attendance_eligible = 10 WHERE first_name = 'Emily' AND last_name = 'Ball';
UPDATE ec_members SET attendance_present = 9, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 10 WHERE first_name = 'Allison' AND last_name = 'Wiseman';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Robin' AND last_name = 'Foxx';
UPDATE ec_members SET attendance_present = 6, attendance_excused = 1, attendance_absent = 1, attendance_eligible = 8 WHERE first_name = 'Rasean' AND last_name = 'Crawley';
UPDATE ec_members SET attendance_present = 7, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Maxwell' AND last_name = 'Morley';
UPDATE ec_members SET attendance_present = 7, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Neal' AND last_name = 'Turpin';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Jeff' AND last_name = 'Noble';
UPDATE ec_members SET attendance_present = 5, attendance_excused = 0, attendance_absent = 3, attendance_eligible = 8 WHERE first_name = 'Janice' AND last_name = 'Dean';
UPDATE ec_members SET attendance_present = 6, attendance_excused = 0, attendance_absent = 2, attendance_eligible = 8 WHERE first_name = 'Brian' AND last_name = 'Russell';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Hallie' AND last_name = 'Rice';
UPDATE ec_members SET attendance_present = 7, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Charlie' AND last_name = 'Horton';
UPDATE ec_members SET attendance_present = 3, attendance_excused = 0, attendance_absent = 5, attendance_eligible = 8 WHERE first_name = 'Idiris' AND last_name = 'Ali';
UPDATE ec_members SET attendance_present = 4, attendance_excused = 0, attendance_absent = 4, attendance_eligible = 8 WHERE first_name = 'Kenneth' AND last_name = 'Washington';
UPDATE ec_members SET attendance_present = 8, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Seth' AND last_name = 'Drake';
UPDATE ec_members SET attendance_present = 7, attendance_excused = 1, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Mike' AND last_name = 'Ward';
UPDATE ec_members SET attendance_present = 6, attendance_excused = 0, attendance_absent = 2, attendance_eligible = 8 WHERE first_name = 'Rick' AND last_name = 'Adams';
UPDATE ec_members SET attendance_present = 2, attendance_excused = 0, attendance_absent = 6, attendance_eligible = 8 WHERE first_name = 'Cori' AND last_name = 'Geter';
UPDATE ec_members SET attendance_present = 3, attendance_excused = 0, attendance_absent = 5, attendance_eligible = 8 WHERE first_name = 'Monica' AND last_name = 'Flowers';
UPDATE ec_members SET attendance_present = 4, attendance_excused = 1, attendance_absent = 3, attendance_eligible = 8 WHERE first_name = 'Stephon' AND last_name = 'Moore';
UPDATE ec_members SET attendance_present = 6, attendance_excused = 2, attendance_absent = 0, attendance_eligible = 8 WHERE first_name = 'Merideth' AND last_name = 'Booth';
UPDATE ec_members SET attendance_present = 4, attendance_excused = 0, attendance_absent = 0, attendance_eligible = 4 WHERE first_name = 'Jessica' AND last_name = 'Haggy';
UPDATE ec_members SET attendance_present = 5, attendance_excused = 0, attendance_absent = 3, attendance_eligible = 8 WHERE first_name = 'Linda' AND last_name = 'Jones';
UPDATE ec_members SET attendance_present = coalesce(attendance_present, 10), attendance_eligible = coalesce(attendance_eligible, 10) WHERE first_name = 'Lisa' AND last_name = 'Tanner Norkus';

-- Phone numbers from PHONES constant
UPDATE ec_members SET phone = COALESCE(phone, '(502) 432-8338') WHERE first_name = 'Jeff' AND last_name = 'Noble';
UPDATE ec_members SET phone = COALESCE(phone, '(502) 407-2349') WHERE first_name = 'Charlie' AND last_name = 'Horton';
UPDATE ec_members SET phone = COALESCE(phone, '(859) 585-3994') WHERE first_name = 'Seth' AND last_name = 'Drake';
UPDATE ec_members SET phone = COALESCE(phone, '(502) 314-8068') WHERE first_name = 'Mike' AND last_name = 'Ward';
UPDATE ec_members SET phone = COALESCE(phone, '(502) 702-1395') WHERE first_name = 'Rick' AND last_name = 'Adams';
UPDATE ec_members SET phone = COALESCE(phone, '(502) 681-6931') WHERE first_name = 'Stephon' AND last_name = 'Moore';

-- Officer roles + officer phones (re-applied, idempotent)
UPDATE ec_members SET officer_role = 'CHAIR', phone = COALESCE(phone, '(502) 931-6721') WHERE first_name = 'Logan' AND last_name = 'Gatti';
UPDATE ec_members SET officer_role = 'VICE_CHAIR', phone = COALESCE(phone, '(502) 295-5435') WHERE first_name = 'Roz' AND last_name = 'Welch';
UPDATE ec_members SET officer_role = 'SECRETARY', phone = COALESCE(phone, NULL) WHERE first_name = 'Brook' AND last_name = 'Benningfield';
UPDATE ec_members SET officer_role = 'TREASURER', phone = COALESCE(phone, '(502) 262-3728') WHERE first_name = 'Linda' AND last_name = 'Jones';

COMMIT;