-- v1 remaining data: candidates, transitions, events, MC priorities, content, month cards
-- Generated 2026-04-21T00:54:12.555Z

BEGIN;

-- Clear existing (idempotent re-run)
DELETE FROM candidates WHERE cycle_year = 2026;

-- STATE_HOUSE
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 28, 2026, 'Pamela Stevenson', 'D', true, false, false, true, 'Running for US Senate 2026 — HD28 open');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 28, 2026, 'Almaria Baker', 'D', false, false, true, true, 'LDP LD28 Chair · unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 29, 2026, 'Kevin Bratcher', 'R', true, false, false, true, 'R incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 29, 2026, 'Cassie Blausey', 'D', false, false, true, true, 'LDP LD29 VC');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 29, 2026, 'Cassie Lyles', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 29, 2026, 'Max Morley', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 29, 2026, 'Mitra Subedi', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 30, 2026, 'Daniel Grossberg', 'D', true, false, true, true, 'On ballot');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 31, 2026, 'Susan Witten', 'R', true, false, false, true, 'Verify current');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 31, 2026, 'Tim Hall', 'D', false, false, true, true, 'Unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 32, 2026, 'Tina Bojanowski', 'D', true, false, true, true, 'Incumbent · unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 33, 2026, 'Jason Nemes', 'R', true, false, false, true, 'R incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 33, 2026, 'Jennifer Hardin', 'D', false, false, true, true, 'LDP LD33 Chair');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 33, 2026, 'Tarah LeBlanc', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 34, 2026, 'Sarah Stalker', 'D', true, false, true, true, 'Incumbent · unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 35, 2026, 'Lisa Willner', 'D', true, false, true, true, 'Incumbent · unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 36, 2026, 'John Hodgson', 'R', true, false, false, true, 'Verify current');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 36, 2026, 'William Zorn', 'D', false, false, true, true, 'Unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 37, 2026, 'Emily Callaway', 'R', true, false, false, true, 'Verify current · no D endorsed yet');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 38, 2026, 'TJ Roberts', 'R', true, false, false, true, 'Verify current');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 38, 2026, 'Rachel Roarx', 'D', false, false, true, true, 'Unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 40, 2026, 'Nima Kulkarni', 'D', true, false, true, true, 'Incumbent · LDP LD40 VC');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 40, 2026, 'Patrick Dunegan', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 41, 2026, 'Mary Lou Marzian', 'D', true, false, true, true, 'Incumbent · unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 42, 2026, 'Keturah Herron', 'D', true, false, false, true, 'Verify — HD42 is a Louisville D seat');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 42, 2026, 'Joshua Watkins', 'D', false, false, true, true, 'Unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 43, 2026, 'Pamela Stevenson', 'D', true, false, false, true, 'Running for US Senate — HD43 may be open');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 43, 2026, 'Joi McAtee', 'D', false, false, true, true, 'LDP LD43 Chair');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 43, 2026, 'Robert Bell', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 44, 2026, 'Joni Jenkins', 'D', true, false, false, true, 'Retiring — open seat 2026');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 44, 2026, 'Beverly Chester-Burton', 'D', false, false, true, true, 'LDP LD44 Chair');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 44, 2026, 'Kenya Wade', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 44, 2026, 'Jesten Slaw', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 46, 2026, 'Al Gentry', 'D', true, false, true, true, 'Incumbent · unopposed in primary');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 48, 2026, 'Ken Fleming', 'R', true, false, false, true, 'Verify current');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 48, 2026, 'Nathan Bellows', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_HOUSE', 48, 2026, 'Suhas Kulkarni', 'D', false, false, true, true, NULL);

-- STATE_SENATE
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_SENATE', 6, 2026, 'Christian Furman', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_SENATE', 6, 2026, 'Chaz Stoess', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_SENATE', 10, 2026, 'Christopher Gatrost', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('STATE_SENATE', 26, 2026, 'Karen Berg', 'D', false, false, true, true, 'Incumbent · unopposed in primary');

-- METRO_COUNCIL
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 11, 2026, 'Melina Hettiaratchi', 'D', false, true, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 15, 2026, 'Jennifer Chappell', 'D', false, true, true, true, 'Incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 17, 2026, 'Markus Winkler', 'D', false, true, true, true, 'Incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 17, 2026, 'Merideth Booth', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 21, 2026, 'Betsy Ruhe', 'D', false, true, true, true, 'Incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 21, 2026, 'Savannah Hughes', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 21, 2026, 'Ben Spalding', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 23, 2026, 'Ainsley Jones', 'D', false, true, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 1, 2026, 'Tammy Hawkins', 'D', false, true, true, true, 'Incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 1, 2026, 'JaRee Gardner', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 3, 2026, 'Kumar Rashad', 'D', false, true, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 3, 2026, 'Shaun Spencer', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 3, 2026, 'Keisha Dorsey', 'D', false, false, true, true, 'Incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 5, 2026, 'Aprile Hearn', 'D', false, true, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 5, 2026, 'Dave Duncan', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 5, 2026, 'Ray ''Sir Friendly'' Barker', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 5, 2026, 'Betty Bailey', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 5, 2026, 'Donna Purvis', 'D', false, false, true, true, 'Incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 7, 2026, 'Paula McCraney', 'D', false, true, true, true, 'Incumbent');
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 9, 2026, 'Alison Brotzge-Elder', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 9, 2026, 'Andrea R. Parr', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 9, 2026, 'Mark England', 'D', false, false, true, true, NULL);
INSERT INTO candidates (office_type, district_number, cycle_year, full_name, party, is_incumbent, is_endorsed, on_primary_ballot, on_general_ballot, notes) VALUES ('METRO_COUNCIL', 9, 2026, 'Charles Todd', 'D', false, false, true, true, NULL);

-- Transitions since June 2025 reorg
DELETE FROM transitions;
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('LD33_VC', 'Charlie Todd', 'Moved out of district', '2025-09-01', 'Larry Owens', (SELECT id FROM ec_members WHERE (first_name || ' ' || last_name) = 'Larry Owens' LIMIT 1), 'FILLED', '2025-10-01');
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('LD43_VC', 'Kristian Edwards', NULL, '2025-10-01', 'Gerald Joiner', (SELECT id FROM ec_members WHERE (first_name || ' ' || last_name) = 'Gerald Joiner' LIMIT 1), 'FILLED', '2025-11-01');
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('LD44_CHAIR', 'Shreeta Waldon', NULL, '2025-10-08', 'Beverly Chester Burton', (SELECT id FROM ec_members WHERE (first_name || ' ' || last_name) = 'Beverly Chester Burton' LIMIT 1), 'FILLED', NULL);
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('LD48_CHAIR', 'Clifton Griffin', NULL, '2025-11-01', NULL, NULL, 'VACANT', NULL);
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('LD42_VC', 'DeWana Hadder', NULL, '2025-12-01', NULL, NULL, 'VACANT', NULL);
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('WOMENS_CLUB_PRES', 'Laura Lydon', NULL, '2025-11-01', 'Jessica Haggy', (SELECT id FROM ec_members WHERE (first_name || ' ' || last_name) = 'Jessica Haggy' LIMIT 1), 'FILLED', '2025-11-01');
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('LYD_PRES', 'Deric Senecal', NULL, '2025-12-01', 'Hallie Rice', (SELECT id FROM ec_members WHERE (first_name || ' ' || last_name) = 'Hallie Rice' LIMIT 1), 'FILLED', NULL);
INSERT INTO transitions (seat_code, previous_holder_name, departure_reason, departed_date, successor_name, successor_id, status, elected_date) VALUES ('VOLUNTEER_CMTE_CO_CHAIR', 'Teresa Macobin', NULL, '2026-04-01', 'Jessica Haggy', (SELECT id FROM ec_members WHERE (first_name || ' ' || last_name) = 'Jessica Haggy' LIMIT 1), 'FILLED', NULL);

-- Signature Events
DELETE FROM events;
INSERT INTO events (type, name, event_date, event_window_description, drive_folder_url, tickets_url) VALUES ('CELEBRATION_OF_DEMOCRACY', 'Celebration of Democracy Dinner', '2027-03-27', 'Spring gala · Last Saturday in March', 'https://drive.google.com/drive/folders/17KbK3cR3NVLep_o5PbY8t_bKm43ki7dM', NULL);
INSERT INTO events (type, name, event_date, event_window_description, drive_folder_url, tickets_url) VALUES ('WOMEN_DELIVER_DEMOCRACY', 'Women Deliver Democracy', NULL, 'Late summer · August 2026', 'https://drive.google.com/drive/folders/1TPT-_obSRP2STS5NteFEGFyrrmss4ueT', NULL);
INSERT INTO events (type, name, event_date, event_window_description, drive_folder_url, tickets_url) VALUES ('DEMS_AT_THE_DOWNS', 'Dems at the Downs', NULL, 'Post-election · Early November 2026', 'https://drive.google.com/drive/folders/1lcYEyzGc0IHzLb51-oawE1-pNSXKwoNj', NULL);

-- Priority Metro Council districts
DELETE FROM metro_races_priority;
INSERT INTO metro_races_priority (mc_number, tier, voter_count, sleeper_dems, independents, strategy_summary_md) VALUES (17, 'HIGHEST', 22782, 3934, 1930, '**MC 17 · Winkler.** 22,782 voters · 6 DEFEND precincts · 3,934 sleeper Dems · 1,930 Independents. 3,934 sleeper Dems are the margin. This is the seat where one summer of disciplined work flips the council.');
INSERT INTO metro_races_priority (mc_number, tier, voter_count, sleeper_dems, independents, strategy_summary_md) VALUES (7, 'HIGH', NULL, NULL, NULL, '**MC 7 · McCraney.** Power Base district — the job is keeping reliable Dems voting and pulling the chase list to the polls.');
INSERT INTO metro_races_priority (mc_number, tier, voter_count, sleeper_dems, independents, strategy_summary_md) VALUES (21, 'HIGH', 23367, 4081, 1978, '**MC 21 · Ruhe.** 23,367 voters · 18 of 25 ACTIVATE precincts · 4,081 sleeper Dems · 1,978 Independents. Wake the Vote district — biggest pool of sleeper Dems in any single MC. Owned by the November cycle.');

-- Content cards for Tour Step 1 orientation
DELETE FROM content_cards WHERE section IN ('tour_step_1', 'tour_step_5', 'commitments');
INSERT INTO content_cards (slug, title, section, body_md, display_order, published) VALUES ('how-we-fit', 'How we fit', 'tour_step_1', 'The Democratic National Committee sets national strategy and funds key priorities. The Kentucky Democratic Party runs statewide elections and provides the playbooks, tools, and legal infrastructure counties operate within. The Louisville Democratic Party is the county-level Executive Committee — we''re the ones who actually organize the 629 precincts in Jefferson County, recruit and endorse local candidates, and deliver turnout in the only place where Kentucky Democrats consistently win.', 10, true) ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, section = EXCLUDED.section, body_md = EXCLUDED.body_md, display_order = EXCLUDED.display_order;
INSERT INTO content_cards (slug, title, section, body_md, display_order, published) VALUES ('five-things-ec-owes', 'Five things every Executive Committee owes its county', 'tour_step_1', '1. **Organize precincts.** Keep Precinct Captains filled and active across all 629 precincts.
2. **Recruit and endorse candidates.** Every winnable seat needs a credible Democrat on the ballot.
3. **Run voter contact.** Canvass, phonebank, and GOTV at scale — both in primaries and November.
4. **Fundraise locally.** KDP and the DNC together cover less than a fifth of party operating costs. The rest is raised in-county.
5. **Train the next generation.** LD Chairs, Precinct Captains, canvassers, and candidates all need onboarding — not assumed competence.', 20, true) ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, section = EXCLUDED.section, body_md = EXCLUDED.body_md, display_order = EXCLUDED.display_order;
INSERT INTO content_cards (slug, title, section, body_md, display_order, published) VALUES ('120-club', 'The $120 Club', 'commitments', 'Every Executive Committee member is expected to join the $120 Club: a minimum personal give of $10 a month plus $500 raised for the party each year. This is the operational baseline — the floor, not the ceiling. Signature events and everything else the party does run on every board member pulling their weight here.

**The math:** $120/year personal + $500/year raise = **$620 per board member floor**. With 55+ voting members, that''s north of $34,000/year just from the floor — and it''s the baseline before any signature event revenue.', 10, true) ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, section = EXCLUDED.section, body_md = EXCLUDED.body_md, display_order = EXCLUDED.display_order;
INSERT INTO content_cards (slug, title, section, body_md, display_order, published) VALUES ('what-this-portal-is', 'What this portal is and isn''t', 'tour_step_1', '**This portal is:** the internal playbook for LDPEC members. A companion to Google Drive (where working docs live) and louisvilledems.com (where the party talks to voters). Source of truth for roster, monthly work, and what''s live this cycle.

**This portal is not:** the public-facing website. That''s louisvilledems.com — different audience, different management, owned by the Communications Committee. If you need something published to voters, route through Comms.', 30, true) ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, section = EXCLUDED.section, body_md = EXCLUDED.body_md, display_order = EXCLUDED.display_order;
INSERT INTO content_cards (slug, title, section, body_md, display_order, published) VALUES ('volunteer-pipeline', 'Volunteer pipeline', 'tour_step_5', 'The Volunteer Committee is the LDP''s countywide deployment system. Jessica Haggy intakes new volunteers, matches them to a committee or LD that fits, plugs them into the Facebook group and Mobilize, and routes them to the priority districts where countywide volunteer hours move the most votes — Metro Council 17 (Winkler), 21 (Ruhe), and 7 (McCraney). LD Chairs and Vice Chairs are the front door of this pipeline. If you don''t pass a volunteer up, they vanish.

1. **Volunteer signs up** (canvass, event, or website form)
2. **Send to Jessica within 7 days** — forward contact + interest
3. **Jessica onboards** — interest survey, LD introduction, Mobilize + FB group
4. **Volunteer gets deployed** — most go to MC17/21/7; some stay in your LD if you have active canvasses.', 10, true) ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, section = EXCLUDED.section, body_md = EXCLUDED.body_md, display_order = EXCLUDED.display_order;

-- Month cards (Rock Star Playbook)
DELETE FROM month_cards WHERE year = 2026;
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (1, 2026, '**January — Planning & refresh.** File your Q4 LD report (due this month). Build next year''s LD calendar. Set personal $120 Club raise target. Platform Committee opens for revision.', 'OFF_CYCLE', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (2, 2026, '**February — Primary prep.** Candidates file; Endorsement process activates. Training Committee runs new LD chair + canvass basics. Celebration of Democracy Dinner ticket push opens.', 'PRIMARY_WINDOW', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (3, 2026, '**March — Canvass kickoff + dinner.** Celebration of Democracy Dinner last Saturday of the month — sell tickets, host a table, bring guests. Canvass waves begin in priority MC overlap districts.', 'PRIMARY_WINDOW', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (4, 2026, '**April — Full canvass cadence.** Weekly canvass shifts in priority MC precincts. Volunteer pipeline in full motion. Endorsements finalize before May.', 'PRIMARY_WINDOW', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (5, 2026, '**May — Primary week + GOTV.** Primary is May 19. Final GOTV in contested districts. File your Q1 LD report. Debrief early in the month.', 'PRIMARY_WINDOW', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (6, 2026, '**June — Regroup + committee joins.** Post-primary debrief at LDPEC. Recruit volunteers who showed up in May onto committees. Plan summer engagement.', 'POST_PRIMARY', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (7, 2026, '**July — Registration drives + PC recruiting.** Summer voter registration campaigns. Start recruiting PC candidates for 2028 Precinct Conventions. File Q2 LD report.', 'SUMMER', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (8, 2026, '**August — Women Deliver Democracy.** WDD this month — push tickets, bring guests, host a table. Continue canvass prep for general election ramp.', 'SUMMER', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (9, 2026, '**September — General canvass kickoff.** Full canvass cadence restarts. Hold the Line precincts get weekly attention. Volunteer pipeline refills for November.', 'GENERAL', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (10, 2026, '**October — Peak GOTV prep.** Daily canvass shifts in priority districts. Early voting starts late-month — drive turnout. File Q3 LD report.', 'GENERAL', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (11, 2026, '**November — Election week + Dems at the Downs.** General election November 3. Final GOTV. Dems at the Downs post-election — celebrate, close out the cycle, thank everyone who showed up.', 'ELECTION_WEEK', true);
INSERT INTO month_cards (month, year, content_md, theme_tag, published) VALUES (12, 2026, '**December — Annual wrap.** Annual LD data review with the LDP Chair. Volunteer appreciation outreach. File Q4 LD report. Set goals for next year. Optional: holiday community engagement.', 'POST_GENERAL', true);

-- Additional settings
INSERT INTO settings (key, value, description) VALUES ('social_facebook', 'https://www.facebook.com/louisvilledems', 'Facebook page') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('social_instagram', 'https://www.instagram.com/louisvilledems/', 'Instagram') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('social_twitter', 'https://x.com/louisvilledems', 'Twitter / X') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('social_bluesky', 'https://bsky.app/profile/louisvilledems.com', 'Bluesky') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('social_threads', 'https://www.threads.net/@louisvilledems', 'Threads') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('social_tiktok', 'https://www.tiktok.com/@louisvilledems', 'TikTok') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('event_intake_url', 'https://loukydemparty.fillout.com/eventrequest', 'One-stop event/comms/asset request form (Beth''s intake)') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('volunteer_signup_url', 'https://act.campaigndeputy.com/LDPVounteerSignup', 'Public volunteer intake form') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('proxy_form_url', 'https://forms.gle/dac7EBMbZXMMdMs59', 'CEC meeting proxy form') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;
INSERT INTO settings (key, value, description) VALUES ('public_calendar_url', 'https://www.louisvilledems.com/calendar', 'Public party calendar') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;

COMMIT;